import React from "react";
import Head from "next/head";

const Create = () => {
  return (
    <>
      <Head>
        <title>DevFolio - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>create</h2>
      </main>

      <footer></footer>
    </>
  );
};

export default Create;
