import React from "react";
import Head from "next/head";
import ProjectCreate from "../../components/ProjectCreate";
import {
  Button,
  Container,
  Group,
  MediaQuery,
  Paper,
  Text,
} from "@mantine/core";
import ProjectAside from "../../components/ProjectAside";
import { useRouter } from "next/router";

const Create = () => {
  const { route } = useRouter();

  const buttonData = {
    save: "Save As Draft",
    publish: "Publish",
  };
  return (
    <>
      <Head>
        <title>DevFolio - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        sx={(theme) => ({
          paddingBottom: "2rem",
          display: "flex",
        })}
      >
        <Container
          sx={(theme) => ({
            [`@media (max-width: ${theme.breakpoints.md}px)`]: {
              padding: 0,
              marginTop: "10rem",
              width: "100%",
            },
          })}
        >
          <Paper
            withBorder
            sx={(theme) => ({
              padding: theme.spacing.md,
              justifyContent: "space-between",
              alignItems: "center",
              display: "flex",
              marginTop: "4rem",
              [`@media (max-width: ${theme.breakpoints.md}px)`]: {
                height: "max-content",
                position: "fixed",
                margin: "auto",
                flexWrap: "wrap",
                top: 60,
                left: 0,
                right: 0,
                zIndex: 99,
              },
            })}
          >
            <Group
              // noWrap
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                width: "100%",
              }}
            >
              <Group
                sx={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  width: "100%",
                }}
              >
                <Text style={{ fontWeight: "bold" }}>Create A New Project</Text>
                <MediaQuery largerThan="lg" styles={{ display: "none" }}>
                  <Text>
                    status:
                    <span style={{ color: "green", fontWeight: 500 }}>
                      {" "}
                      published
                    </span>
                  </Text>
                </MediaQuery>
              </Group>
              <MediaQuery largerThan="md" styles={{ display: "none" }}>
                <Group direction="row" noWrap>
                  <Button
                    variant="gradient"
                    gradient={{ from: "indigo", to: "cyan" }}
                  >
                    Save As Draft
                  </Button>
                  <Button
                    variant="gradient"
                    gradient={{ from: "teal", to: "lime", deg: 105 }}
                  >
                    Publish
                  </Button>
                </Group>
              </MediaQuery>
            </Group>
          </Paper>

          <Paper
            withBorder
            sx={(theme) => ({
              padding: theme.spacing.md,
              width: "100%",
              marginInline: "-.1rem",
              display: "flex",
              flexDirection: "column",
              gap: "1rem",
            })}
          >
            <ProjectCreate />
          </Paper>
        </Container>
        <ProjectAside buttonData={buttonData} />
      </Container>
    </>
  );
};

export default Create;
