import React from "react";
import Head from "next/head";
import Image from "next/image";

const Categories = () => {
  return (
    <div className="container">
      <Head>
        <title>DevFolio - Categories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </div>
  );
};

export default Categories;
