import React from "react";
import Head from "next/head";
import Image from "next/image";
const Techs = () => {
  return (
    <div className="container">
      <Head>
        <title>DevFolio - Techs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </div>
  );
};

export default Techs;
